version: '3'
services:
  shadowsocks:
    image: xiocode/shadowsocks-libev
    ports:
      - "2345:8388"
    environment:
      - METHOD=chacha20-ietf-poly1305
      - PASSWORD=1234567890
      - OBFS_OPTS=obfs=tls;obfs-host=www.bing.com
    restart: always
