version: '2'
services:
  shadowsocks:
    image: xiocode/shadowsocks-libev
    ports:
      - "5432:8388/tcp"
      - "5432:8388/udp"
    environment:
      - METHOD="chacha20-ietf-poly1305"
      - PASSWORD="1234567890"
      - OBFS_OPTS="obfs=tls;obfs-host=www.bing.com"
    restart: always
